cuda: False
ngpu: 0
gpu_id: '0'
model: 'VAMetric'
init_model: './checkpoints/VAMetric_state_epoch10.pth'
data_dir: './Train'     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 4
batchSize: 40
checkpoint_folder: './checkpoints'
topk: 5